config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  namespace :admin do
    constraints AdminConstraint do
      mount Sidekiq::Web => '/sidekiq'
    end
  end

  root 'pages#home'

  resources :products, only: [:index, :show]
  resources :blogs, only: [:index, :show]
  resources :messages, only: [:create]

  get 'home', to: 'pages#home'

end

app/models/admin_user.rb
# == Schema Information
#
# Table name: admin_users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  created_at             :datetime
#  updated_at             :datetime
#

class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/blog.rb
# == Schema Information
#
# Table name: blogs
#
#  id         :integer          not null, primary key
#  title      :string
#  body       :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Blog < ActiveRecord::Base
  paginates_per 10

  scope :latest, -> {order("updated_at desc")}
end

app/models/image.rb
# == Schema Information
#
# Table name: images
#
#  id                :integer          not null, primary key
#  image_owner_id    :integer
#  image_owner_type  :string
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  file_file_name    :string
#  file_content_type :string
#  file_file_size    :integer
#  file_updated_at   :datetime
#

class Image < ActiveRecord::Base
  has_attached_file :file, :styles => { :large => "500x500", :thumb => "280x210!" }
  validates_attachment :file, :presence => true,
    :content_type => { :content_type => /\Aimage\/.*\Z/ },
    :size => { :in => 0..20.megabytes }

  belongs_to :image_owner, polymorphic: true
end

app/models/message.rb
# == Schema Information
#
# Table name: messages
#
#  id           :integer          not null, primary key
#  name         :string
#  email        :string
#  phone_number :string
#  content      :text
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Message < ActiveRecord::Base
  validates :email, allow_blank: true, format: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  validates :content, presence: true
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id           :integer          not null, primary key
#  title        :string
#  description  :text
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  product_type :integer          default(0), not null
#

class Product < ActiveRecord::Base
  enum product_type: [ :charge, :battery ]

  has_many :images, as: :image_owner
  accepts_nested_attributes_for :images, allow_destroy: true

  scope :latest, -> {order("updated_at desc")}
end

app/models/settings.rb
class Settings < Settingslogic
  source "#{Rails.root}/config/application.yml"
  namespace Rails.env
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def setup_products
    @products = Rails.cache.fetch [Product.latest.first, 'all'] do
      Product.latest.all
    end
  end

  def setup_slide_news
    @slide_blogs = Rails.cache.fetch [Blog.latest.first, 'lasted-3'] do
      Blog.latest.limit(3)
    end
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

  layout "home"
  before_action :setup_products, only: [:index, :show]
  before_action :setup_slide_news, only: [:show]

  def index
    @blogs = Blog.latest.page(params[:page])
  end

  def show
    @blog = Blog.find(params[:id])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def create
    message = Message.new(message_params)
    if message.save
      MessageNotifier.new_message(message).deliver_later
      render json: {message: "发送成功, 感谢您的关注"}
    else
      render json: {message: message.errors.to_a}, status: 400
    end
  end

  private

  def message_params
    params.require(:message).permit(:name, :email, :phone_number, :content)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  layout "home"
  before_action :setup_products, only: [:home]
  before_action :setup_slide_news, only: [:home]

  def home
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  layout "home"
  before_action :setup_products, only: [:index, :show]

  def index
  end

  def show
    @product = Product.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def format_time_for_blogs(time)
    time.strftime("%Y-%m-%d %H:%M")
  end

  def content_summary(body, length=120)
    body[0..length-1]
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/blogs/_blog_details.html.slim
/! profile begins
- cache ['blog-detail', @blog] do
  section#page-blog-details.page-blog-details
    .container
      header.section-header
        h2.section-title = @blog.title
        .spacer
        p.section-subtitle
      .row
        .col-md-12
          .blog-post-metadata
            span.blog-post-date
              i.fa.fa-calendar
              = format_time_for_blogs(@blog.updated_at)
          .blog-post-content
            = @blog.body
/! profile ends

app/views/blogs/_blog_list.html.slim
/! blog-list begins
section#page-blog-list.page-blog-list
  .container
    header.section-header
      h2.section-title 新闻 | News
      .spacer
      p.section-subtitle
    - @blogs.each do |blog|
      - cache ['blog-list-item', blog] do
        .row
          .col-md-12.blog-item
            h4
              = link_to blog.title, blog_path(blog)
            .blog-post-metadata
              span.blog-post-date
                i.fa.fa-calendar
                = format_time_for_blogs(blog.updated_at)
            .blog-post-content-summary
              = content_summary(blog.body)
              = link_to blog_path(blog) do
                span ... more
    = paginate @blogs
/! blog-list ends

app/views/blogs/index.html.slim
- content_for :navbar_items do
  li
    = link_to "首页 | Home", root_path
  li
    = link_to "产品展示 | Products", products_path
  li
    a href="#page-contact"  联系我们 | Contact Us

= render 'blog_list'
= render 'shared/portfolio'
= render 'shared/contact'

app/views/blogs/show.html.slim
- content_for :navbar_items do
  li
    = link_to "首页 | Home", root_path
  li
    = link_to "更多新闻 | Other News", blogs_path
  li
    = link_to "产品展示 | Products", products_path
  li
    a href="#page-contact"  联系我们 | Contact Us

= render 'blog_details'
= render 'shared/news'
= render 'shared/portfolio'
= render 'shared/contact'

app/views/layouts/application.html.slim
doctype html
html
  head
    meta charset="utf-8"
    meta content="IE=edge" http-equiv="X-UA-Compatible"
    meta content="width=device-width, initial-scale=1.0" name="viewport"
    meta content="康煜电器科技" name="author"
    meta content="宁波市北仑康煜电器科技有限公司是浙江一家专注于电动牙刷生产、批发的公司。我们的电动牙刷价格公道，质量过硬，在市场上享有良好的口碑。联系电话：0574-86138686" name="description"
    - if content_for?(:head_title)
      = content_for(:head_title)
    - else
      title 浙江电动牙刷厂家|宁波电动牙刷供应商|牙刷批发价格-宁波市北仑康煜电器科技有限公司
    = csrf_meta_tags
    /![if lt IE 9]
      = javascript_include_tag 'html5shiv'
      = javascript_include_tag 'respond'
  body class="#{controller_name}-#{action_name}"
    .navbar.navbar-default.navbar-static-top role="navigation"
      .container
        .home-logo.pull-left
          = link_to root_path do
            i.fa.fa-home.fa-2x
        .navbar-header
          button.navbar-toggle.collapsed data-target=".navbar-collapse" data-toggle="collapse" type="button"
            span.sr-only Toggle navigation
            span.icon-bar
            span.icon-bar
            span.icon-bar
        .navbar-collapse.collapse
          ul#main-menu.nav.navbar-nav
            = content_for :navbar_items
    .fullpage
      == yield
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'

app/views/layouts/home.html.slim
doctype html
html
  head
    meta charset="utf-8"
    meta content="IE=edge" http-equiv="X-UA-Compatible"
    meta content="width=device-width, initial-scale=1.0" name="viewport"
    meta content="康煜电器科技" name="author"
    meta content="宁波市北仑康煜电器科技有限公司是浙江一家专注于电动牙刷生产、批发的公司。我们的电动牙刷价格公道，质量过硬，在市场上享有良好的口碑。联系电话：0574-86138686" name="description"
    - if content_for?(:head_title)
      = content_for(:head_title)
    - else
      title 浙江电动牙刷厂家|宁波电动牙刷供应商|牙刷批发价格-宁波市北仑康煜电器科技有限公司
    = csrf_meta_tags
    /![if lt IE 9]
      = javascript_include_tag 'html5shiv'
      = javascript_include_tag 'respond'
  body class="#{controller_name}-#{action_name}"
    .navbar.navbar-default.navbar-static-top role="navigation"
      .container
        .home-logo.pull-left
          = link_to root_path do
            i.fa.fa-home.fa-2x
        .navbar-header
          button.navbar-toggle.collapsed data-target=".navbar-collapse" data-toggle="collapse" type="button"
            span.sr-only Toggle navigation
            span.icon-bar
            span.icon-bar
            span.icon-bar
        .navbar-collapse.collapse
          ul#main-menu.nav.navbar-nav
            = content_for :navbar_items
    .fullpage
      == yield
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'

app/views/message_notifier/new_message.html.erb
收到询盘信息 (from http://www.nb-kydq.com):
  姓名: <%= @message.name %>
  Email: <%= @message.email %>
  电话: <%= @message.phone_number %>
  内容: <%= @message.content %>

  点击<%= link_to "链接", admin_messages_url %>， 去管理台

app/views/pages/home.html+phone.slim
- content_for :navbar_items do
  li
    a href="#fullpage-welcome" data-menuanchor="fullpage-welcome" 首页 | Homepage
  li
    a href="#fullpage-profile" data-menuanchor="fullpage-profile" 公司介绍 | Company Profile
  li
    a href="#fullpage-portfolio" data-menuanchor="fullpage-portfolio" 最新产品 | Latest Products
  li
    a href="#fullpage-news" data-menuanchor="fullpage-news" 新闻 | News
  li
    a href="#fullpage-contact" data-menuanchor="fullpage-contact" 联系我们 | Contact Us

= render 'shared/welcome'
= render 'shared/profile'
= render 'shared/portfolio_mobile'
= render 'shared/news_mobile'
= render 'shared/contact'

app/views/pages/home.html.slim
- content_for :navbar_items do
  li
    a href="#fullpage-welcome" data-menuanchor="fullpage-welcome" 首页 | Homepage
  li
    a href="#fullpage-profile" data-menuanchor="fullpage-profile" 公司介绍 | Company Profile
  li
    a href="#fullpage-portfolio" data-menuanchor="fullpage-portfolio" 最新产品 | Latest Products
  li
    a href="#fullpage-news" data-menuanchor="fullpage-news" 新闻 | News
  li
    a href="#fullpage-contact" data-menuanchor="fullpage-contact" 联系我们 | Contact Us

= render 'shared/welcome'
= render 'shared/profile'
= render 'shared/portfolio'
= render 'shared/news'
= render 'shared/contact'

app/views/products/_product_details.html.slim
/! product-dtails begins
- cache ['product-details', @product] do
  section#page-product-details.page-product-details
    .container
      header.section-header
        h2.section-title = @product.title
        .spacer
        p.section-subtitle
      .row
        .col-md-6.col-xs12
          .profile
            = image_tag @product.images.first.file.url(:large)
        .col-md-6
          .production-description
            = @product.description.presence || "没有描述"
/! product-dtails ends

app/views/products/_product_list.html.slim
/! portfolio begins
section#page-portfolio.page-portfolio
  .container
    .row
      header.section-header
        h2.section-title
          span 最新产品 | Latest Products
        .spacer
        p.section-subtitle
      #grid-controls-wrapper
        ul.nav.nav-pills.center-pills.grid-controls
          li.active.filter
            a data-filter="*" href="javascript:void(0)"  全部 ALL
          li.filter
            a data-filter=".charge" href="javascript:void(0)" 充电型 CHARGE
          li.filter
            a data-filter=".battery" href="javascript:void(0)"  干电池型 BATTERY
      div.grid-outsider
        ul.grid.grid-wrapper
          - @products.each do |product|
            - cache ['product-list-item', product] do
              li.mix class=product.product_type
                = link_to product_url(product) do
                  = image_tag product.images.first.file.url(:thumb)
                  h5.product-title = product.title
/! portfolio ends

app/views/products/index.html.slim
- content_for :head_title do
  title = "产品展示-宁波市北仑康煜电器科技有限公司"

- content_for :navbar_items do
  li
    = link_to "首页 | Home", root_path
  li
    = link_to "新闻 | News", blogs_path
  li
    a href="#page-contact" 联系我们 | Contact Us


= render 'shared/portfolio'
= render 'shared/contact'

app/views/products/show.html.slim
- content_for :head_title do
  title = "#{@product.title}-宁波市北仑康煜电器科技有限公司"

- content_for :navbar_items do
  li
    = link_to "首页 | Home", root_path
  li
    = link_to "产品展示 | Products", products_path
  li
    a href="#page-contact"  联系我们 | Contact Us

= render 'product_details'
= render 'shared/portfolio'
= render 'shared/contact'

app/views/shared/_contact.html.slim
/! contact begins
section#page-contact.page-contact
  .container
    header.section-header
      h2.section-title
        span 联系我们 | Contact Us
      .spacer
      p.section-subtitle
    .row
      .col-md-5.col-xs-12.contact-info
        h3 联系信息
        p
          i.fa.fa-map-marker
          |  宁波市北仑区大矸镇俞王村172号
        p
          i.fa.fa-phone
          |  13906690282 | 0574-86138686
        p
          i.fa.fa-fax
          |  0574-86139706 (FAX)
        p
          i.fa.fa-envelope-o
          |  9448228@qq.com
      .col-md-7.hidden-xs
        h3 给我们写信
        /! Configure the contact form by adding your email address on mail/contact_me.php line 17
        = form_for Message.new, class: "form-horizontal" do |f|
          .control-group
            label.control-label for="name"  姓名
            .controls
              = f.text_field :name, class: "form-control input-lg", placeholder: "您的姓名"
          .control-group
            label.control-label for="email"  Email 地址
            .controls
              = f.text_field :email, class: "form-control input-lg", placeholder: "您的 Email 地址"
          .control-group
            label.control-label for="phone_number"  电话号码
            .controls
              = f.text_field :phone_number, class: "form-control input-lg", placeholder: "您的电话号码"
          .control-group
            label.control-label for="content"  内容
            .controls
              = f.text_area :content, class: "form-control input-lg", rows: "8", placeholder: "请输入内容"
          .form-actions
            = f.submit "提交", class: "btn btn-default btn-lg btn-block"
        /! End contact-form
    /! End row
/! contact ends

app/views/shared/_news.html.slim
/! news begins
section#page-news.page-news
  .container
    header.section-header
      h2.section-title
        span 新闻 | News
      .spacer
      p.section-subtitle
    .row
      - @slide_blogs.each do |blog|
        - cache ['news-item', blog] do
          .col-md-4.clearfix
            article.blogs
              header
                h3 = link_to blog.title, blog_path(blog)
                p
                  i.fa.fa-calendar
                  = format_time_for_blogs(blog.updated_at)
                p = content_summary(blog.body)
                = link_to blog_path(blog) do
                  span ... more
    .row
      .goto-list
        = link_to "更多文章 ...", blogs_path
/! news ends

app/views/shared/_news_mobile.html.slim
/! news begins
section.section#page-news.page-news data-anchor='fullpage-news'
  .container
    header.section-header
      h2.section-title
        span 新闻 | News
      .spacer
      p.section-subtitle
    .row
      - blog = @first_blog
      .col-md-12.clearfix
        article.blogs
          header
            h3 = link_to blog.title, blog_path(blog)
            p
              i.fa.fa-calendar
              = format_time_for_blogs(blog.updated_at)
            p = content_summary(blog.body)
            = link_to blog_path(blog) do
              span ... more
    .goto-list
      = link_to "更多文章 ...", blogs_path
/! news ends

app/views/shared/_portfolio.html.slim
/! portfolio begins
section#page-portfolio.page-portfolio
  .container
    .row
      header.section-header
        h2.section-title
          span 最新产品 | Latest Products
        .spacer
        p.section-subtitle
      #grid-controls-wrapper
        ul.nav.nav-pills.center-pills.grid-controls
          li.active.filter
            a data-filter="*" href="javascript:void(0)"  全部 ALL
          li.filter
            a data-filter=".charge" href="javascript:void(0)" 充电型 CHARGE
          li.filter
            a data-filter=".battery" href="javascript:void(0)"  干电池型 BATTERY
      div.grid-outsider
        ul.grid.grid-wrapper
          - @products.each do |product|
            - cache ['product-list-item', product] do
              li.mix class=product.product_type
                = link_to product_url(product) do
                  = image_tag product.images.first.file.url(:thumb)
                  h5.product-title = product.title
    - if controller_name == 'pages' && action_name == 'home'
      .goto-list
        = link_to "更多产品 ...", products_path
/! portfolio ends

app/views/shared/_portfolio_mobile.html.slim
/! portfolio begins
section.section#page-portfolio.page-portfolio data-anchor='fullpage-portfolio'
  .container
    .row
      header.section-header
        h2.section-title
          span 最新产品 | Latest Products
        .spacer
        p.section-subtitle

      .col-xs-12.clearfix
        - product = @first_product
        - cache ['product-inner-item', product] do
          .mix class=product.product_type
            = link_to product_url(product) do
              = image_tag product.images.first.file.url(:thumb)
              h5.product-title = product.title
    .goto-list
      = link_to "更多产品 ...", products_path

/! portfolio ends

app/views/shared/_product_inner.html.slim
.row
  header.section-header
    h2.section-title
      span 最新产品 | Latest Products
    .spacer
    p.section-subtitle
  - products.each do |product|
    .col-md-4.col-xs-12.clearfix
      - cache ['product-inner-item', product] do
        .mix class=product.product_type
          = link_to product_url(product) do
            = image_tag product.images.first.file.url(:thumb)
            h5.product-title = product.title
.goto-list
  = link_to "更多产品 ...", products_path

app/views/shared/_profile.html.slim
/! profile begins
section#page-profile.page-profile
  .container
    header.section-header
      h2.section-title 公司简介 | Company Profile
      .spacer
      p.section-subtitle
    .row
      .col-md-3.col-xs-12
        .profile
          img alt="profile" src="img/intro.jpg"
      .col-md-9.col-xs-12
        p 宁波市北仑康煜电器科技有限公司建于2012年5月座落在美丽的海都之城宁波市北仑区,交通十分便捷。其前身是一家纯代工企业，为许多小家电企业产品设计、精密模具制造等加工为主的企业。
        p 现完全按照现代股份公司模式设立，定位为一家专业生产电动牙刷的企业。公司主要生产高档的电动牙刷、各种小家电研发与制造。已与国外客商建立长期合作关系，产品远销香港、日本、美国等国家和地区。
        p 公司以电子商务为核心渠道，努力减少流通环节，给广大客户提供高性价比产品，为生活创造美！
/! profile ends

app/views/shared/_social_icons.slim
.social-icons
  a.btn.btn-round.btn-clear.btn-qq href="tencent://message/?uin=9448228"
    i.fa.fa-qq
  a.btn.btn-round.btn-clear.btn-email href="mailto:9448228@qq.com"
    i.fa.fa-envelope
  a.btn.btn-round.btn-clear.btn-taobao target="_blank" href="http://liangxinggrhl.tmall.com/shop/view_shop.htm?spm=a230r.1.14.6.3usjrz&user_number_id=2165780832&v=1"
    = image_tag '/img/iconfont-taobao.png', class: 'taobao-normal'
    = image_tag '/img/iconfont-taobao-active.png', class: 'taobao-active'
  a.btn.btn-round.btn-clear.btn-taobao target="_blank" href="http://amos1.taobao.com/msg.ww?v=2&uid=亮星旗舰店&s=1"
    = image_tag '/img/iconfont-wangwang.png', class: 'taobao-normal'
    = image_tag '/img/iconfont-wangwang-active.png', class: 'taobao-active'
  / a.btn.btn-round.btn-clear.btn-twitter href="https://twitter.com/"
  /   i.fa.fa-twitter
  / a.btn.btn-round.btn-clear.btn-facebook href="https://www.facebook.com/"
  /   i.fa.fa-facebook
  / a.btn.btn-round.btn-clear.btn-dribbble href="https://www.dribbble.com/"
  /   i.fa.fa-dribbble
  / a.btn.btn-round.btn-clear.btn-instagram href="https://www.instagram.com/"
  /   i.fa.fa-instagram
  / a.btn.btn-round.btn-clear.btn-linkedin href="https://www.linkedin.com/"
  /   i.fa.fa-linkedin-square
  / a.btn.btn-round.btn-clear.btn-pinterest href="https://www.pinterest.com/"
  /   i.fa.fa-pinterest
  / a.btn.btn-round.btn-clear.btn-google href="https://www.google.com/"
  /   i.fa.fa-google-plus

app/views/shared/_welcome.html.slim
/! welcome begins
section.section#page-welcome.page-welcome data-anchor='fullpage-welcome'
  div
    ul.slider-controls
      li
        a#vegas-next.next href="#"
      li
        a#vegas-prev.prev href="#"
  .container
    .row
      header.centered
        h1 宁波市北仑康煜电器科技有限公司
        p 专业的声波牙刷制造商
      = render 'shared/social_icons'
      a.btn.btn-default.hire-me href="#fullpage-contact"  联系我
/! welcome ends